plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.3'
    id 'io.spring.dependency-management' version '1.1.6'
}

group = 'com.connectus'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)  // Java 21 kullanılıyor
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor  // Lombok gibi compileOnly bağımlılıkları için annotationProcessor desteği ekleniyor
    }
}

repositories {
    mavenCentral()  // Maven Central repository'si eklenmiş
}

ext {
    set('springCloudVersion', "2023.0.3")  // Spring Cloud versiyonu
}

dependencies {
    // Kafka starter bağımlılığı
    implementation 'org.springframework.kafka:spring-kafka'

    // JSON desteği (isteğe bağlı)
    implementation 'com.fasterxml.jackson.core:jackson-databind'

    // Zookeeper bağımlılığına versiyon ekleniyor
    implementation 'org.apache.zookeeper:zookeeper:3.8.0'  // Versiyon burada belirtilmeli

    // Diğer bağımlılıklar
    implementation 'org.springframework.boot:spring-boot-starter-amqp'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    // implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.cloud:spring-cloud-starter-gateway-mvc'
    implementation 'com.auth0:java-jwt:4.4.0'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.5.0'

    // Lombok (derleme zamanında çalışacak)
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'  // Lombok için annotation processor ekleniyor

    // Geliştirme araçları (devtools)
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    // Çalışma zamanında kullanılacak PostgreSQL bağımlılığı
    runtimeOnly 'org.postgresql:postgresql'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

tasks.named('test') {
    useJUnitPlatform()  // Testler için JUnit platformu kullanılıyor
}
