# MinIO'nun resmi Docker imajını kullan
FROM minio/minio:latest

# Ortam değişkenlerini ayarla (Admin kullanıcı adı ve şifresi)
ENV MINIO_ROOT_USER=user
ENV MINIO_ROOT_PASSWORD=password

# Web konsolunun portu
EXPOSE 9000  # MinIO API portu
EXPOSE 9001  # MinIO Konsol portu

# MinIO'yu başlatma komutu ve konsolun 9001'de çalışmasını sağla
CMD ["minio", "server", "/data", "--console-address", ":9001"]
