server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/connectusdb
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: java.teamworks@gmail.com
    password: fdzw xckg crim hjvu
    protocol: smtp
    tls: true
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

connectus:
  secret:
    secret-key: ${JAVA_14_SECRET_KEY:defaultSecretKey}
    issuer: ${JAVA_14_ISSUER:defaultIssuer}
