server:
  port: 9090
spring:
  datasource:
    url: jdbc:postgresql://dpg-ct87itpopnds73bu3920-a.oregon-postgres.render.com:5432/connectusauthdb
    username: connectusauthdb_user
    password: QkUuiVGArWwxb9HATS2vgtVTUmlnQBBb
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: java.teamworks@gmail.com
    password: qzlq qqhh fhdz ylhk
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.debug: true

connectus:
  secret:
    secret-key: ${JAVA_14_SECRET_KEY:defaultSecretKey}
    issuer: ${JAVA_14_ISSUER:defaultIssuer}

aws:
  region: ${AWS_REGION}
  s3:
    buckets:
      customer: ${AWS_BUCKET_NAME}
  credentials:
    access-key-id: ${AWS_ACCESS_KEY_ID}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY}
